name: JavaScript Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  # Runs the QUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Logs debug information about the GitHub Action runner.
  # - Installs npm dependencies.
  # - Run the WordPress QUnit tests.
  # - Ensures version-controlled files are not modified or deleted.
  test-js:
    name: QUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Grunt
        run: npm install -g grunt-cli

      - name: Install npm Dependencies
        run: npm ci

      - name: Run QUnit tests
        run: npm run grunt qunit:compiled

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code
