name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run composer install
        run: composer install

      - name: Build and Push Docker Image
        run: |
          cd YeSyuen/wordpress-develop
          docker build -t nginx:alpine
