name: Build CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install mysql-server
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: yesyuen/wordpress
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create wp-config file
      run: cp wp-config-sample.php wp-config.php

    - name: Create wp-test-config file
      run: cp wp-tests-config-sample.php wp-tests-config.php
    - name: update composer
      run: composer update -W
    - name: Run PHPUnit tests
      run: phpunit
