name: JavaScript Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  # Runs the QUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Logs debug information about the GitHub Action runner.
  # - Installs npm dependencies.
  # - Run the WordPress QUnit tests.
  # - Ensures version-controlled files are not modified or deleted.
  test-js:
    name: QUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Grunt
        run: npm install -g grunt-cli

      - name: Install npm Dependencies
        run: npm ci

      - name: Run QUnit tests
        run: npm run grunt qunit:compiled
