name: Build CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run composer install
        run: composer install

      - name: Build and Push Docker Image
        run: |
          docker build ./wordpress-develop -t nginx:alpine
