name: PHPUnit Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust to your PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
