name: PHPUnit Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress_develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust to your PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: copy
        run: cp wp-config-sample.php wp-config.php
      - name: copy
        run: cp wp-tests-config-sample.php wp-tests-config.php

      - name:
        run: |
          sed -i 's/your_db_host/mysql/' wp-tests-config.php
          sed -i 's/your_db_name/test_database/' wp-tests-config.php
          sed -i 's/your_db_user/root/' wp-tests-config.php
          sed -i 's/your_db_password/root_password/' wp-tests-config.php


      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
