name: PHPUnit Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust to your PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: copy
        run: cp wp-config-sample.php wp-config.php
      - name: copy
        run: cp wp-tests-config-sample.php wp-tests-config.php

      - name: Check MySQL Service Status
        run: sudo service mysql status
      - name: Check MySQL Docker Container Status
        run: docker ps -a | grep mysql
      - name: Test MySQL Connection (Verbose)
        run: mysql -h 127.0.0.1 -u root -proot_password -e "SELECT 1" -v


      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
